language: python
python:
- '2.7'
- '3.5'
sudo: true
before_install:
- pip install numpy
- pip install scipy
- pip install scikit-learn
script:
- python setup.py test
notifications:
  email: false
deploy:
  provider: pypi
  user: johnding
  password: 
  on:
    tags: true
    all_branches: true
    distributions: sdist bdist_wheel
    repo: phoenixding/scdiff
    python: '2.7'
env:
  global:
    secure: 1R3nvgPrfeJNnaXmmL3+kgGccaQnrcYOHZjzDhbyVfSzSBXxVr+LKNWJybMjn16064FD9FZt83RhBoCtCoSb5/Igt0Fxy3Sn5ZWjAFqcQVD83W2PWy4LDLVLJVBZ022K9ZFj21T8XkgzR+WEP0FJuZyXo7+ywBxeWEL5rq0UYDhaDtWzlaLATHT4+5XGku9Dauj0jsYZ1XmwLIOc9eeNdDHveFLzQ/io8uQE0sFvWftJredwJf8RlaQWCagEwklEmincE1U4vjyLrzXu4fklFVGwWZU8SJSBfhZRSDmCcnJxWwlpVf7HKNqNPF2IISn6/o7ym1ssbsq3rCTzgk8t1iqqTIWI0RH6CveLrdJGCXTXmjGIwcokpKziZXYfEr1BbQH1IzARkNGCJ0aJ2WH4KG6+Gw99VjVU3KRROaYkIwZJ4P2s4i4zCYwgmlUzhPmhbt9QL3H3EaK6Vro6N9L0RRXpumVilxGTCoDhu8yW++5Yk6o/b1NmAHoNBLoXV1GWMmzW5PeT8lWbT4Ekg5r9Bubs9Uzw5WqcKn2AGJwMKjG17spTbt190Kh9vw8latoKqTjX1GV6VjA+AqMmvsBHNnJ4tqhBlfGZ6fNSuoC2dw1nHFdEcBEBLBp381y/vOAgzJex9IbCiEdjHa3E5bdYLwYSIA3B3OM15tRLg5Ogz5c=
