language: python
python:
- '2.7'
- '3.5'
sudo: true
before_install:
- pip install numpy
- pip install scipy
- pip install scikit-learn
script:
- python setup.py test
notifications:
  email: false
deploy:
  provider: pypi
  user: johnding
  password:
      secure: jLWuzNa/HxDhbYWjd5G0n2IkKiBPuUhKc9jMCmUGJ8PmqMRxCJVGsO5g+dLcmhgeGKvYrLC5QqU5fildBewdP6Sh8sKZuhGj6yp/UapbrIKeEznrCi6d8koTn5fv9EKACgYa/M/VV4g5FyOCi0u7Io5/1Tebl8AlDyJbbylmqQw5eeeH96VJpwcD+Q+LUj8K3eLC2vIMm5YymkKSDW3UiuXkHWKHropVJb1/IshxOXM2pcUpcu+Y6SEns/FYeuwdGpMzuOLOZIhFhpO7DXB8QyRiShj5B5pOL8KLJH5+EBvR2BGaLuYLL8B/A7Ms8WiRGgi6A/3Cg9OWsjbF1FOel/SNLhLHPkq4cf31VNFspecgznNrF0dopwzJxPpDz4hbXXlGMxU+ZavDwKeZL02nJrYB/I+OJDI214fTOL2K0TEtqCJRLc1N5kljkuOWReQ7YP6m3vLL+KE7EuFVzx/56RHpyOzSu7nNcguY9JLsxY6bFO0PqcpJQ7ce5/djpET9B9bEAufqwZKd6qokkFA53YXRXoGA6uy0d5plmq3TbRx1KKsfk5AtYSWe9yDLb/9sPzf3J9u32yVGTpE8LQa7eWcXf18UbzJjw1EchslJlrTHCwfBe1jIW8T3pa41ceo7K4gLJM6HC+OLxhfJrqJtMw+HBhFTATVqiXr/3eoDBLw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: phoenixding/scdiff
    python: '2.7'
